// Command heatmap is the m2 inspect benchmark rebuilt on pkg/heatmap. For each
// scenario it diagnoses the full manifests (baseline), then removes each field
// in turn (heatmap.Remove) and re-diagnoses, scoring saliency = baseline minus
// reduced accuracy, and writes an \input-able saliency table to paper/.
//
//	go run ./cmd/heatmap [flags]
package main

import (
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/mikolajsemeniuk/kubelean/pkg/dataset"
	"github.com/mikolajsemeniuk/kubelean/pkg/heatmap"
	"github.com/mikolajsemeniuk/kubelean/pkg/providers"
)

type diagnosis struct {
	FaultClass string `json:"fault_class"`
}

var (
	host, model, out      string
	k, numCtx, numPredict int
	temp                  float64

	// schema constrains the model to clean JSON with a fixed fault_class vocabulary
	// (mirrors the scenarios' FaultClass labels + NoFaultFound). Extend the enum when
	// you add scenarios.
	schema = map[string]any{
		"type": "object",
		"properties": map[string]any{
			"fault_class": map[string]any{
				"type": "string",
				"enum": []string{"SelectorLabelMismatch", "SecretRefNotFound", "NoFaultFound"},
			},
			"offending_field": map[string]any{"type": "string"},
		},
		"required": []string{"fault_class", "offending_field"},
	}

	// systemPrompt frames the root-cause task. The schema enforces the JSON shape and
	// the fault_class vocabulary, so scoring is a plain string compare. The "reduced"
	// framing is load-bearing: variants have fields removed for the ablation, and we
	// must stop the model from reading an absent field as a fault in itself.
	systemPrompt = `You are a senior Kubernetes SRE performing root-cause analysis.
You are given one or more manifests as returned by "kubectl get -o yaml".
The manifests may have been deliberately reduced — some fields removed to save context.
Treat every manifest as valid and well-formed: a missing field is not itself a fault.
Diagnose the root cause only from the information that is present.
At most one root-cause fault is present; the manifests may also be healthy.
fault_class must be one of: SelectorLabelMismatch, SecretRefNotFound, NoFaultFound.
Set offending_field to the YAML path most responsible, or "none".`
)

func main() {
	flag.StringVar(&host, "host", "http://localhost:11434", "Ollama host")
	flag.StringVar(&model, "model", "qwen2.5:7b-instruct", "model name")
	flag.StringVar(&out, "out", "paper", "output directory")
	flag.IntVar(&k, "k", 10, "samples per variant (seed = 0..k-1)")
	flag.Float64Var(&temp, "temp", 0.7, "sampling temperature (>0 so seeds give varied draws)")
	flag.IntVar(&numCtx, "num-ctx", 8192, "context window — avoids silent truncation of multi-doc prompts")
	flag.IntVar(&numPredict, "num-predict", 256, "max output tokens")
	flag.Parse()

	ctx := context.Background()
	client := providers.NewOllama(host)

	// Pin the exact weights for the paper: a tag can be re-pulled and change.
	digest, err := client.Digest(ctx, model)
	if err != nil {
		log.Printf("warning: could not read model digest: %v", err)
		digest = "unknown"
	}

	var b strings.Builder
	b.WriteString("% Auto-generated by cmd/heatmap — do not edit.\n")
	b.WriteString("% \\input-able fragment; requires \\usepackage{booktabs}.\n")
	b.WriteString(fmt.Sprintf("%% model: %s @ %s ; k=%d ; temp=%.2f ; num_ctx=%d ; num_predict=%d\n", model, digest, k, temp, numCtx, numPredict))
	b.WriteString("% Saliency = baseline accuracy − reduced accuracy, each a fraction over k samples\n")
	b.WriteString("% (seed = 0..k-1, all else fixed). Bold = saliency > 0 (placeholder; a CI test replaces it).\n")
	b.WriteString("% Valid flags whether the reduced variant is still a schema-valid manifest.\n")
	b.WriteString("% Validity is a covariate, NOT a gate: every variant is scored under the\n")
	b.WriteString("% reduced-view prompt (reduce() ships field-removed YAML in production too), but\n")
	b.WriteString("% Valid=no is reported as a separate population — a high saliency there is often\n")
	b.WriteString("% tautological (the removed field WAS the fault locus, e.g. a required name).\n")
	b.WriteString("\\begin{tabular}{lllcr}\n\\toprule\n")
	b.WriteString("Scenario & Kind & Field & Valid & Saliency \\\\\n\\midrule\n")

	for _, s := range dataset.Scenarios() {
		start := time.Now()
		in := providers.ChatInput{
			Model:   model,
			Prompt:  systemPrompt + "\n\nManifests:\n" + s.YAML,
			Format:  schema,
			Options: providers.ChatOptions{Temperature: temp, NumCtx: numCtx, NumPredict: numPredict},
		}
		base, err := accuracy(ctx, client, in, s.FaultClass, k)

		targets, err := heatmap.Keys(s.YAML)
		if err != nil {
			log.Fatalf("%s keys: %v", s.Name, err)
		}

		fmt.Printf("%s: baseline acc=%.2f (k=%d), ablating %d targets…\n", s.Name, base, k, len(targets))
		invalid := 0
		for _, t := range targets {
			reduced, err := heatmap.Remove(s.YAML, t)
			if err != nil {
				log.Fatalf("%s remove %s: %v", s.Name, t.Pointer, err)
			}

			// Validity is a covariate, not a gate: every variant is scored under the
			// reduced-view prompt, but invalid ones are flagged so a tautological
			// saliency (the removed field WAS the fault) is not read as real signal.
			valid, _, err := heatmap.Valid(reduced)
			if err != nil {
				log.Fatalf("%s validate %s: %v", s.Name, t.Pointer, err)
			}
			if !valid {
				invalid++
			}

			variant := in
			variant.Prompt = systemPrompt + "\n\nManifests:\n" + reduced
			acc, err := accuracy(ctx, client, variant, s.FaultClass, k)
			if err != nil {
				log.Fatalf("%s chat: %v", s.Name, err)
			}

			saliency := base - acc
			field := "\\texttt{" + escapeTeX(t.Pointer) + "}"
			if saliency > 0 {
				field = "\\textbf{" + field + "}"
			}

			mark := "yes"
			if !valid {
				mark = "no"
			}

			fmt.Fprintf(&b, "%s & %s & %s & %s & %.2f \\\\\n", escapeTeX(s.Name), escapeTeX(t.Kind), field, mark, saliency)
		}

		fmt.Printf("  %d/%d variants invalid (scored, flagged separately)\n", invalid, len(targets))

		elapsed := time.Since(start)
		fmt.Printf("  %s took %dm%02ds\n", s.Name, int(elapsed.Minutes()), int(elapsed.Seconds())%60)
	}

	b.WriteString("\\bottomrule\n\\end{tabular}\n")
	if err := os.MkdirAll(out, 0o755); err != nil {
		log.Fatal(err)
	}

	path := filepath.Join(out, "heatmap.gen.tex")
	if err := os.WriteFile(path, []byte(b.String()), 0o644); err != nil {
		log.Fatalf("write %s: %v", path, err)
	}

	fmt.Printf("wrote %s\n", path)
}

func escapeTeX(s string) string {
	in := []string{
		"\\", "\\textbackslash{}",
		"_", "\\_", "%", "\\%", "&", "\\&", "#", "\\#",
		"$", "\\$", "{", "\\{", "}", "\\}",
		"~", "\\textasciitilde{}", "^", "\\textasciicircum{}",
	}

	return strings.NewReplacer(in...).Replace(s)
}

// accuracyOf runs k samples (seed = 0..k-1, everything else fixed) and returns
// the fraction whose fault_class matches want. Fixed seeds make the run
// reproducible; temp > 0 makes the draws actually differ. A sample that fails to
// parse counts as incorrect for now — a stopgap until item #8 buckets parse
// failures and reports parse_rate as its own number.
func accuracy(ctx context.Context, client *providers.Ollama, in providers.ChatInput, want string, k int) (float64, error) {
	correct := 0
	for i := 0; i < k; i++ {
		in.Options.Seed = int64(i)
		res, err := client.Chat(ctx, in)
		if err != nil {
			return 0, err
		}

		var d diagnosis
		if err := json.Unmarshal([]byte(res.Response), &d); err != nil {
			continue
		}

		if d.FaultClass == want {
			correct++
		}
	}

	return float64(correct) / float64(k), nil
}
