// Command heatmap is the m2 inspect benchmark rebuilt on pkg/heatmap. For each
// scenario it diagnoses the full manifests (baseline), then removes each field
// in turn (heatmap.Remove) and re-diagnoses, scoring saliency = baseline minus
// reduced accuracy, and writes an \input-able saliency table to paper/.
//
//	go run ./cmd/heatmap [flags]
package main

import (
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"strings"

	"github.com/mikolajsemeniuk/kubelean/pkg/dataset"
	"github.com/mikolajsemeniuk/kubelean/pkg/heatmap"
	"github.com/mikolajsemeniuk/kubelean/pkg/providers"
)

type diagnosis struct {
	FaultClass string `json:"fault_class"`
}

var (
	host, model, out string
	seed             int64
	temp             float64

	// schema constrains the model to clean JSON with a fixed fault_class vocabulary
	// (mirrors the scenarios' FaultClass labels + NoFaultFound). Extend the enum when
	// you add scenarios.
	schema = map[string]any{
		"type": "object",
		"properties": map[string]any{
			"fault_class": map[string]any{
				"type": "string",
				"enum": []string{"SelectorLabelMismatch", "SecretRefNotFound", "NoFaultFound"},
			},
			"offending_field": map[string]any{"type": "string"},
		},
		"required": []string{"fault_class", "offending_field"},
	}

	// systemPrompt frames the root-cause task. The schema enforces the JSON shape and
	// the fault_class vocabulary, so scoring is a plain string compare.
	systemPrompt = `You are a senior Kubernetes SRE performing root-cause analysis.
You are given one or more manifests as returned by "kubectl get -o yaml".
At most one root-cause fault is present; the manifests may also be healthy.
fault_class must be one of: SelectorLabelMismatch, SecretRefNotFound, NoFaultFound.
Set offending_field to the YAML path most responsible, or "none".`
)

func main() {
	flag.StringVar(&host, "host", "http://localhost:11434", "Ollama host")
	flag.StringVar(&model, "model", "qwen2.5:7b-instruct", "model name")
	flag.StringVar(&out, "out", "paper", "output directory")
	flag.Int64Var(&seed, "seed", 0, "sampling seed")
	flag.Float64Var(&temp, "temp", 0, "sampling temperature")
	flag.Parse()

	ctx := context.Background()
	client := providers.NewOllama(host)

	var b strings.Builder
	b.WriteString("% Auto-generated by cmd/heatmapv2 — do not edit.\n")
	b.WriteString("% \\input-able fragment; requires \\usepackage{booktabs}.\n")
	b.WriteString("% Saliency = baseline accuracy − accuracy with the field removed; bold = carries signal.\n")
	b.WriteString("\\begin{tabular}{lllr}\n\\toprule\n")
	b.WriteString("Scenario & Kind & Field & Saliency \\\\\n\\midrule\n")

	for _, s := range dataset.Scenarios() {
		in := providers.ChatInput{
			Model:   model,
			Prompt:  systemPrompt + "\n\nManifests:\n" + s.YAML,
			Format:  schema,
			Options: providers.ChatOptions{Temperature: temp, Seed: seed},
		}
		res, err := client.Chat(ctx, in)
		if err != nil {
			log.Fatalf("%s baseline: %v", s.Name, err)
		}

		var base diagnosis
		if err := json.Unmarshal([]byte(res.Response), &base); err != nil {
			log.Fatalf("%s baseline: %v", s.Name, err)
		}

		correct := base.FaultClass == s.FaultClass
		targets, err := heatmap.Keys(s.YAML)
		if err != nil {
			log.Fatalf("%s keys: %v", s.Name, err)
		}

		fmt.Printf("%s: baseline correct=%v, ablating %d targets…\n", s.Name, correct, len(targets))
		for _, t := range targets {
			reduced, err := heatmap.Remove(s.YAML, t)
			if err != nil {
				log.Fatalf("%s remove %s: %v", s.Name, t.Pointer, err)
			}

			in.Prompt = systemPrompt + "\n\nManifests:\n" + reduced
			res, err := client.Chat(ctx, in)
			if err != nil {
				log.Fatalf("%s diagnose %s: %v", s.Name, t.Pointer, err)
			}

			var d diagnosis
			if err := json.Unmarshal([]byte(res.Response), &d); err != nil {
				log.Fatalf("%s diagnose %s: %v", s.Name, t.Pointer, err)
			}

			saliency := b2f(correct) - b2f(d.FaultClass == s.FaultClass)
			field := "\\texttt{" + escapeTeX(t.Pointer) + "}"
			if saliency > 0 {
				field = "\\textbf{" + field + "}"
			}

			fmt.Fprintf(&b, "%s & %s & %s & %.2f \\\\\n", escapeTeX(s.Name), escapeTeX(t.Kind), field, saliency)
		}
	}

	b.WriteString("\\bottomrule\n\\end{tabular}\n")
	if err := os.MkdirAll(out, 0o755); err != nil {
		log.Fatal(err)
	}

	path := filepath.Join(out, "heatmap.gen.tex")
	if err := os.WriteFile(path, []byte(b.String()), 0o644); err != nil {
		log.Fatalf("write %s: %v", path, err)
	}

	fmt.Printf("wrote %s\n", path)
}

func escapeTeX(s string) string {
	in := []string{
		"\\", "\\textbackslash{}",
		"_", "\\_", "%", "\\%", "&", "\\&", "#", "\\#",
		"$", "\\$", "{", "\\{", "}", "\\}",
		"~", "\\textasciitilde{}", "^", "\\textasciicircum{}",
	}

	return strings.NewReplacer(in...).Replace(s)
}

func b2f(b bool) float64 {
	if b {
		return 1
	}
	return 0
}
