// Command accuracy runs the main RCA benchmark across distillation profiles and
// reports accuracy + mean tokens overall and by difficulty. It carries the
// headline results: H1 (pruning improves RCA up to a sweet spot), H2 (random-drop
// at equal budget is far worse -> it's WHICH fields are kept), and H3 (the
// goal-conditioned L4 profile, when enabled). Writes paper/accuracy.gen.tex.
//
// Usage:
//
//	go run ./cmd/accuracy -model qwen2.5:7b-instruct -n 3 -k 3 [-l4]
package main

import (
	"context"
	"flag"
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/schollz/progressbar/v3"

	"github.com/mikolajsemeniuk/kubelean/pkg/bench"
	"github.com/mikolajsemeniuk/kubelean/pkg/distill"
	"github.com/mikolajsemeniuk/kubelean/pkg/eval"
	"github.com/mikolajsemeniuk/kubelean/pkg/faults"
)

func main() {
	model := flag.String("model", "qwen2.5:7b-instruct", "Ollama model")
	n := flag.Int("n", 3, "instances per class")
	k := flag.Int("k", 3, "RCA repeats per instance per profile")
	temp := flag.Float64("temp", 0.4, "sampling temperature")
	l3thresh := flag.Float64("l3thresh", 0.0, "L3 entropy threshold")
	l4 := flag.Bool("l4", false, "include the L4 goal-conditioned profile (needs an embed model)")
	embedModel := flag.String("embed", "nomic-embed-text", "Ollama embedding model for L4")
	l4thresh := flag.Float64("l4thresh", 0.5, "L4 cosine-similarity keep threshold")
	texOut := flag.String("tex", "paper/accuracy.gen.tex", "write the LaTeX tables here (empty = skip)")
	flag.Parse()

	instances := faults.GenerateAll(*n)
	profiles := []string{bench.L0, bench.L1, bench.L2, bench.L3}
	if *l4 {
		profiles = append(profiles, bench.L4)
	}
	profiles = append(profiles, bench.Rand)

	var embed distill.EmbedFunc
	if *l4 {
		embed = distill.NewEmbedder(*embedModel).Embed
		fmt.Printf("L4 grounding via %s (threshold %.2f)\n", *embedModel, *l4thresh)
	}
	r := bench.NewRenderer(bench.Corpus(instances), embed, *l3thresh, *l4thresh)

	client := eval.NewRCAClient(*model, *temp)
	diag := func(ctx context.Context, y string) (string, int, error) {
		d, ptok, _, err := client.Diagnose(ctx, y)
		return d.RootCauseLabel, ptok, err
	}

	fmt.Printf("model=%s  n=%d  k=%d  temp=%.2f  profiles=%s  instances=%d\n\n",
		*model, *n, *k, *temp, strings.Join(profiles, "/"), len(instances))

	renderBar := progressbar.NewOptions(len(instances),
		progressbar.OptionSetDescription("render"), progressbar.OptionSetWriter(os.Stderr), progressbar.OptionClearOnFinish())
	rcaBar := progressbar.NewOptions(len(instances)*len(profiles)**k,
		progressbar.OptionSetDescription("RCA"), progressbar.OptionSetWriter(os.Stderr),
		progressbar.OptionShowCount(), progressbar.OptionSetPredictTime(true),
		progressbar.OptionThrottle(100*time.Millisecond), progressbar.OptionClearOnFinish())

	results, err := bench.Run(context.Background(), instances, profiles, r, diag, *k,
		bench.Progress{Render: func() { _ = renderBar.Add(1) }, RCA: func() { _ = rcaBar.Add(1) }})
	if err != nil {
		fatal("run: %v", err)
	}

	overall := map[string]*bench.Acc{}
	byDiff := map[string]*bench.Acc{} // "difficulty/profile"
	for _, p := range profiles {
		overall[p] = &bench.Acc{}
	}
	for _, res := range results {
		overall[res.Profile].Add(res)
		key := res.Difficulty + "/" + res.Profile
		if byDiff[key] == nil {
			byDiff[key] = &bench.Acc{}
		}
		byDiff[key].Add(res)
	}

	fmt.Println("== overall ==")
	for _, p := range profiles {
		fmt.Printf("  %-6s %5.1f%%  %5d tok\n", p, overall[p].Pct(), overall[p].MeanTok())
	}
	fmt.Println("\n== by difficulty ==")
	for _, d := range []string{"easy", "hard"} {
		fmt.Printf("  [%s] ", d)
		for _, p := range profiles {
			if a := byDiff[d+"/"+p]; a != nil {
				fmt.Printf(" %s=%.0f%%", p, a.Pct())
			}
		}
		fmt.Println()
	}

	if *texOut != "" {
		if err := bench.WriteFile(*texOut, accuracyTeX(*model, *n, *k, *temp, profiles, overall, byDiff)); err != nil {
			fatal("write tex: %v", err)
		}
		fmt.Printf("\nwrote LaTeX: %s\n", *texOut)
	}
}

func accuracyTeX(model string, n, k int, temp float64, profiles []string, overall, byDiff map[string]*bench.Acc) string {
	var b strings.Builder
	caption := fmt.Sprintf("(\\texttt{%s}, $n{=}%d$, $k{=}%d$, $T{=}%.2f$)", bench.TexEscape(model), n, k, temp)

	fmt.Fprintf(&b, "%% accuracy.gen.tex — AUTO-GENERATED by cmd/accuracy. DO NOT EDIT BY HAND.\n")
	fmt.Fprintf(&b, "%% Requires \\usepackage{booktabs}.\n\n")

	fmt.Fprintf(&b, "\\begin{table}[t]\n  \\centering\n")
	fmt.Fprintf(&b, "  \\caption{RCA accuracy and mean prompt tokens per distillation profile %s.}\n", caption)
	fmt.Fprintf(&b, "  \\label{tab:accuracy-overall}\n")
	fmt.Fprintf(&b, "  \\begin{tabular}{lrr}\n    \\toprule\n    Profile & Acc. (\\%%) & Tokens \\\\\n    \\midrule\n")
	for _, p := range profiles {
		fmt.Fprintf(&b, "    %s & %.1f & %d \\\\\n", p, overall[p].Pct(), overall[p].MeanTok())
	}
	fmt.Fprintf(&b, "    \\bottomrule\n  \\end{tabular}\n\\end{table}\n\n")

	fmt.Fprintf(&b, "\\begin{table}[t]\n  \\centering\n")
	fmt.Fprintf(&b, "  \\caption{RCA accuracy (\\%%) by difficulty %s.}\n", caption)
	fmt.Fprintf(&b, "  \\label{tab:accuracy-difficulty}\n")
	fmt.Fprintf(&b, "  \\begin{tabular}{l%s}\n    \\toprule\n    Difficulty", strings.Repeat("r", len(profiles)))
	for _, p := range profiles {
		fmt.Fprintf(&b, " & %s", p)
	}
	fmt.Fprintf(&b, " \\\\\n    \\midrule\n")
	for _, d := range []string{"easy", "hard"} {
		if byDiff[d+"/"+profiles[0]] == nil {
			continue
		}
		fmt.Fprintf(&b, "    %s", d)
		for _, p := range profiles {
			fmt.Fprintf(&b, " & %.0f", byDiff[d+"/"+p].Pct())
		}
		fmt.Fprintf(&b, " \\\\\n")
	}
	fmt.Fprintf(&b, "    \\bottomrule\n  \\end{tabular}\n\\end{table}\n")
	return b.String()
}

func fatal(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "accuracy: "+format+"\n", args...)
	os.Exit(1)
}
