// Command noise sweeps the two independent noise axes and reports how RCA holds
// up under each, raw (L0) vs distilled (L1/L2): the volume axis adds structural
// bloat (managedFields), the mislead axis adds semantic distractors (stale
// annotations naming other faults). The finding: structural bloat is inert,
// semantic distractors hurt L0 while distillation that strips them protects RCA.
// Writes paper/noise.gen.tex.
//
// Usage:
//
//	go run ./cmd/noise -model qwen2.5:7b-instruct -n 3 -k 3 -volumes 0,4,8,16 -mislead 0,1,2,4,8
package main

import (
	"context"
	"flag"
	"fmt"
	"os"
	"strconv"
	"strings"
	"time"

	"github.com/schollz/progressbar/v3"

	"github.com/mikolajsemeniuk/kubelean/pkg/bench"
	"github.com/mikolajsemeniuk/kubelean/pkg/eval"
	"github.com/mikolajsemeniuk/kubelean/pkg/faults"
)

// point is the overall accuracy + mean tokens of one profile at one noise level.
type point struct {
	level int
	acc   map[string]float64
	tok   map[string]int
}

func main() {
	model := flag.String("model", "qwen2.5:7b-instruct", "Ollama model")
	n := flag.Int("n", 3, "instances per class")
	k := flag.Int("k", 3, "RCA repeats per instance per profile")
	temp := flag.Float64("temp", 0.4, "sampling temperature")
	l3thresh := flag.Float64("l3thresh", 0.0, "L3 entropy threshold (unused profiles aside)")
	volumes := flag.String("volumes", "0,4,8,16", "comma-separated structural-noise levels")
	mislead := flag.String("mislead", "0,1,2,4,8", "comma-separated semantic-distractor levels")
	texOut := flag.String("tex", "paper/noise.gen.tex", "write the LaTeX tables here (empty = skip)")
	flag.Parse()

	volList := parseInts(*volumes)
	misList := parseInts(*mislead)
	profiles := []string{bench.L0, bench.L1, bench.L2}

	client := eval.NewRCAClient(*model, *temp)
	diag := func(ctx context.Context, y string) (string, int, error) {
		d, ptok, _, err := client.Diagnose(ctx, y)
		return d.RootCauseLabel, ptok, err
	}
	base := faults.GenerateAll(*n)

	totalRCA := (len(volList) + len(misList)) * len(base) * len(profiles) * *k
	bar := progressbar.NewOptions(totalRCA,
		progressbar.OptionSetDescription("noise"), progressbar.OptionSetWriter(os.Stderr),
		progressbar.OptionShowCount(), progressbar.OptionSetPredictTime(true),
		progressbar.OptionThrottle(100*time.Millisecond), progressbar.OptionClearOnFinish())

	run := func(volume, mis int) point {
		inst := bench.Inflate(base, volume, mis)
		r := bench.NewRenderer(bench.Corpus(inst), nil, *l3thresh, 0)
		results, err := bench.Run(context.Background(), inst, profiles, r, diag, *k,
			bench.Progress{RCA: func() { _ = bar.Add(1) }})
		if err != nil {
			fatal("run: %v", err)
		}
		accs := map[string]*bench.Acc{}
		for _, p := range profiles {
			accs[p] = &bench.Acc{}
		}
		for _, res := range results {
			accs[res.Profile].Add(res)
		}
		pt := point{level: volume + mis, acc: map[string]float64{}, tok: map[string]int{}}
		for _, p := range profiles {
			pt.acc[p] = accs[p].Pct()
			pt.tok[p] = accs[p].MeanTok()
		}
		return pt
	}

	fmt.Printf("model=%s  n=%d  k=%d  temp=%.2f  volumes=%v  mislead=%v\n\n", *model, *n, *k, *temp, volList, misList)

	var volPts, misPts []point
	for _, v := range volList {
		pt := run(v, 0)
		pt.level = v
		volPts = append(volPts, pt)
	}
	for _, m := range misList {
		pt := run(0, m)
		pt.level = m
		misPts = append(misPts, pt)
	}

	printSweep("volume (structural bloat)", profiles, volPts)
	printSweep("mislead (semantic distractors)", profiles, misPts)

	if *texOut != "" {
		if err := bench.WriteFile(*texOut, noiseTeX(*model, *n, *k, *temp, profiles, volPts, misPts)); err != nil {
			fatal("write tex: %v", err)
		}
		fmt.Printf("\nwrote LaTeX: %s\n", *texOut)
	}
}

func printSweep(title string, profiles []string, pts []point) {
	fmt.Printf("\n== %s ==\n", title)
	for _, pt := range pts {
		fmt.Printf("  level=%-3d", pt.level)
		for _, p := range profiles {
			fmt.Printf("  %s=%.0f%%(%dtok)", p, pt.acc[p], pt.tok[p])
		}
		fmt.Println()
	}
}

func noiseTeX(model string, n, k int, temp float64, profiles []string, volPts, misPts []point) string {
	var b strings.Builder
	fmt.Fprintf(&b, "%% noise.gen.tex — AUTO-GENERATED by cmd/noise. DO NOT EDIT BY HAND.\n")
	fmt.Fprintf(&b, "%% Requires \\usepackage{booktabs}.\n\n")
	sweepTable(&b, "volume", "Structural-noise (managedFields) robustness", "tab:noise-volume", model, n, k, temp, profiles, volPts)
	b.WriteString("\n")
	sweepTable(&b, "mislead", "Semantic-distractor (stale annotation) robustness", "tab:noise-mislead", model, n, k, temp, profiles, misPts)
	return b.String()
}

func sweepTable(b *strings.Builder, axis, caption, label, model string, n, k int, temp float64, profiles []string, pts []point) {
	fmt.Fprintf(b, "\\begin{table}[t]\n  \\centering\n")
	fmt.Fprintf(b, "  \\caption{%s: RCA accuracy (\\%%) and mean tokens vs.\\ %s level (\\texttt{%s}, $n{=}%d$, $k{=}%d$, $T{=}%.2f$).}\n",
		caption, axis, bench.TexEscape(model), n, k, temp)
	fmt.Fprintf(b, "  \\label{%s}\n", label)
	fmt.Fprintf(b, "  \\begin{tabular}{r%s}\n    \\toprule\n    %s", strings.Repeat("rr", len(profiles)), axis)
	for _, p := range profiles {
		fmt.Fprintf(b, " & %s acc & %s tok", p, p)
	}
	fmt.Fprintf(b, " \\\\\n    \\midrule\n")
	for _, pt := range pts {
		fmt.Fprintf(b, "    %d", pt.level)
		for _, p := range profiles {
			fmt.Fprintf(b, " & %.0f & %d", pt.acc[p], pt.tok[p])
		}
		fmt.Fprintf(b, " \\\\\n")
	}
	fmt.Fprintf(b, "    \\bottomrule\n  \\end{tabular}\n\\end{table}\n")
}

func parseInts(csv string) []int {
	var out []int
	for _, s := range strings.Split(csv, ",") {
		s = strings.TrimSpace(s)
		if s == "" {
			continue
		}
		v, err := strconv.Atoi(s)
		if err != nil {
			fatal("bad integer %q in list", s)
		}
		out = append(out, v)
	}
	return out
}

func fatal(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "noise: "+format+"\n", args...)
	os.Exit(1)
}
