apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Name }}
  labels:
    app: {{ .App }}
spec:
  capacity:
    storage: {{ .Storage }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .StorageClass }}
  hostPath:
    path: {{ .Path }}
