apiVersion: apps/v1
kind: ReplicaSet
metadata:
  {{- if .Created }}
  creationTimestamp: "{{ .Created }}"
  {{- end }}
  {{- if .Generation }}
  generation: {{ .Generation }}
  {{- end }}
  name: {{ .Name }}
  namespace: {{ .Namespace }}
  labels:
    app: {{ .App }}
  {{- if .ResourceVersion }}
  resourceVersion: "{{ .ResourceVersion }}"
  {{- end }}
  {{- if .UID }}
  uid: {{ .UID }}
  {{- end }}
spec:
  replicas: {{ .Replicas }}
  selector:
    matchLabels:
      app: {{ .SelectorApp }}
  template:
    metadata:
      {{- if .Created }}
      creationTimestamp: null
      {{- end }}
      labels:
        app: {{ .PodApp }}
    spec:
      containers:
        - name: {{ .ContainerName }}
          image: {{ .Image }}
          ports:
            - containerPort: {{ .ContainerPort }}
{{- if eq .Status "healthy" }}
status:
  availableReplicas: {{ .Replicas }}
  fullyLabeledReplicas: {{ .Replicas }}
  observedGeneration: {{ .Generation }}
  readyReplicas: {{ .Replicas }}
  replicas: {{ .Replicas }}
{{- else if eq .Status "failing" }}
status:
  fullyLabeledReplicas: {{ .Replicas }}
  observedGeneration: {{ .Generation }}
  replicas: {{ .Replicas }}
{{- end }}
