apiVersion: v1
kind: Service
metadata:
  {{- if .Created }}
  creationTimestamp: "{{ .Created }}"
  {{- end }}
  name: {{ .Name }}
  namespace: {{ .Namespace }}
  labels:
    app: {{ .App }}
  {{- if .ResourceVersion }}
  resourceVersion: "{{ .ResourceVersion }}"
  {{- end }}
  {{- if .UID }}
  uid: {{ .UID }}
  {{- end }}
spec:
  type: {{ .Type }}
  {{- if .Headless }}
  clusterIP: None
  {{- else if .ClusterIP }}
  clusterIP: {{ .ClusterIP }}
  clusterIPs:
    - {{ .ClusterIP }}
  {{- end }}
  {{- if .Created }}
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  {{- end }}
  selector:
    app: {{ .SelectorApp }}
  ports:
    - port: {{ .Port }}
      targetPort: {{ .TargetPort }}
      {{- if .NodePort }}
      nodePort: {{ .NodePort }}
      {{- end }}
      protocol: TCP
{{- if .Status }}
status:
  loadBalancer: {}
{{- end }}
