apiVersion: v1
kind: ServiceAccount
metadata:
  {{- if .Created }}
  creationTimestamp: "{{ .Created }}"
  {{- end }}
  name: {{ .Name }}
  namespace: {{ .Namespace }}
  labels:
    app: {{ .App }}
  {{- if .ResourceVersion }}
  resourceVersion: "{{ .ResourceVersion }}"
  {{- end }}
  {{- if .UID }}
  uid: {{ .UID }}
  {{- end }}
automountServiceAccountToken: true
