// Command tokens reports the token reduction of each distillation level
// (L0 raw -> L1 lossless -> L2 static -> L3 corpus-entropy), averaged over the
// generated fault catalog and counted with the model's own tokenizer (Ollama
// prompt_eval_count). No RCA, no accuracy — just cost. Writes paper/tokens.gen.tex.
//
// Usage:
//
//	go run ./cmd/tokens -model qwen2.5:7b-instruct -n 3
package main

import (
	"context"
	"flag"
	"fmt"
	"os"
	"strings"

	"github.com/schollz/progressbar/v3"

	"github.com/mikolajsemeniuk/kubelean/pkg/bench"
	"github.com/mikolajsemeniuk/kubelean/pkg/distill"
	"github.com/mikolajsemeniuk/kubelean/pkg/faults"
)

func main() {
	model := flag.String("model", "qwen2.5:7b-instruct", "Ollama model whose tokenizer counts tokens")
	n := flag.Int("n", 3, "instances per class to average over")
	l3thresh := flag.Float64("l3thresh", 0.0, "L3 entropy threshold")
	texOut := flag.String("tex", "paper/tokens.gen.tex", "write the LaTeX table here (empty = skip)")
	flag.Parse()

	instances := faults.GenerateAll(*n)
	r := bench.NewRenderer(bench.Corpus(instances), nil, *l3thresh, 0)
	counter := distill.NewOllamaCounter(*model)
	ctx := context.Background()

	profiles := []string{bench.L0, bench.L1, bench.L2, bench.L3}
	sum := map[string]int{}

	bar := progressbar.NewOptions(len(instances)*len(profiles),
		progressbar.OptionSetDescription("tokens"),
		progressbar.OptionSetWriter(os.Stderr),
		progressbar.OptionShowCount(),
		progressbar.OptionClearOnFinish(),
	)
	for _, inst := range instances {
		for _, p := range profiles {
			y, err := r.Bundle(ctx, inst.Resources, p, inst.Truth.Goal, 0.6)
			if err != nil {
				fatal("render %s: %v", p, err)
			}
			t, err := counter.Count(ctx, y)
			if err != nil {
				fatal("count %s: %v (is `ollama serve` running?)", p, err)
			}
			sum[p] += t
			_ = bar.Add(1)
		}
	}

	mean := func(p string) float64 { return float64(sum[p]) / float64(len(instances)) }
	base := mean(bench.L0)

	fmt.Printf("model=%s  n=%d  instances=%d\n\n", *model, *n, len(instances))
	fmt.Printf("%-4s %10s %8s\n", "lvl", "mean tok", "vs L0")
	for _, p := range profiles {
		fmt.Printf("%-4s %10.0f %7.0f%%\n", p, mean(p), 100*mean(p)/base)
	}

	if *texOut != "" {
		if err := bench.WriteFile(*texOut, tokensTeX(*model, *n, len(instances), profiles, mean, base)); err != nil {
			fatal("write tex: %v", err)
		}
		fmt.Printf("\nwrote LaTeX: %s\n", *texOut)
	}
}

func tokensTeX(model string, n, instances int, profiles []string, mean func(string) float64, base float64) string {
	var b strings.Builder
	fmt.Fprintf(&b, "%% tokens.gen.tex — AUTO-GENERATED by cmd/tokens. DO NOT EDIT BY HAND.\n")
	fmt.Fprintf(&b, "%% Run: model=%s n=%d instances=%d. Requires \\usepackage{booktabs}.\n\n", model, n, instances)
	fmt.Fprintf(&b, "\\begin{table}[t]\n  \\centering\n")
	fmt.Fprintf(&b, "  \\caption{Mean prompt tokens per distillation level over the generated fault catalog (\\texttt{%s}, $n{=}%d$ per class). L1 is lossless by construction.}\n", bench.TexEscape(model), n)
	fmt.Fprintf(&b, "  \\label{tab:tokens}\n")
	fmt.Fprintf(&b, "  \\begin{tabular}{lrr}\n    \\toprule\n")
	fmt.Fprintf(&b, "    Level & Mean tokens & vs.\\ L0 \\\\\n    \\midrule\n")
	for _, p := range profiles {
		fmt.Fprintf(&b, "    %s & %.0f & %.0f\\%% \\\\\n", p, mean(p), 100*mean(p)/base)
	}
	fmt.Fprintf(&b, "    \\bottomrule\n  \\end{tabular}\n\\end{table}\n")
	return b.String()
}

func fatal(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "tokens: "+format+"\n", args...)
	os.Exit(1)
}
