// The three paper figures, rendered from the same cell population as the
// tables (same gate, same verdicts):
//
//	fieldprofile.gen.tex  the cross-scenario field profile — the m3 input and
//	                      the anti-circularity defense: each field-key's marginal
//	                      behaviour aggregated across scored scenarios.
//	heatmapfig.gen.tex    the contrast map as a TikZ figure: one dense grid per
//	                      Kind, orange = signal, grey = no marginal signal.
//	manifestfig.gen.tex   the heatmap painted ON the manifest: the flagship
//	                      scenario's YAML, line by line, coloured by verdict.
package main

import (
	"fmt"
	"math"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/mikolajsemeniuk/kubelean/pkg/dataset"
	"github.com/mikolajsemeniuk/kubelean/pkg/heatmap"
	"gopkg.in/yaml.v3"
)

// figCtx carries the renderer's shared state into the figure writers.
type figCtx struct {
	cells       map[string]cell
	order       []string
	faultClass  map[string]string
	gated       map[string]string
	baseCorrect map[string]int
	baseTotal   map[string]int
	floor       map[string]float64
	verdict     func(key string) string
}

func (f *figCtx) sal(c cell) float64 {
	return frac(f.baseCorrect[c.scenario], f.baseTotal[c.scenario]) - frac(c.matchFault, c.total)
}

func (f *figCtx) scored(c cell) bool {
	return f.faultClass[c.scenario] != dataset.FaultNoFault && f.gated[c.scenario] == ""
}

// writeFieldProfile emits the per-field-key aggregate across scored scenarios:
// how often the key was measured, how often it was a deciding locus, and its
// saliency distribution where it was NON-deciding — a field's marginal signal
// independent of where the fault was injected, which is the direct input for
// m3 and the defense against "the heatmap just recovers your fault design".
func (f *figCtx) writeFieldProfile(outDir string) {
	type prof struct {
		kind, field         string
		measured, deciding  int
		nSig                int
		sum, minSal, maxSal float64
		nonDeciding         int
	}
	profs := map[string]*prof{}
	var keys []string
	for _, key := range f.order {
		c := f.cells[key]
		if !f.scored(c) {
			continue
		}
		pk := c.kind + "\x00" + c.field
		p := profs[pk]
		if p == nil {
			p = &prof{kind: c.kind, field: c.field, minSal: math.Inf(1), maxSal: math.Inf(-1)}
			profs[pk] = p
			keys = append(keys, pk)
		}
		p.measured++
		if c.deciding {
			p.deciding++
			continue
		}
		s := f.sal(c)
		p.nonDeciding++
		p.sum += s
		p.minSal = math.Min(p.minSal, s)
		p.maxSal = math.Max(p.maxSal, s)
		if f.verdict(key) == "signal" {
			p.nSig++
		}
	}

	sort.Slice(keys, func(i, j int) bool {
		a, b := profs[keys[i]], profs[keys[j]]
		if a.nSig != b.nSig {
			return a.nSig > b.nSig
		}
		am, bm := frac1(a.sum, a.nonDeciding), frac1(b.sum, b.nonDeciding)
		if am != bm {
			return am > bm
		}
		if a.kind != b.kind {
			return a.kind < b.kind
		}
		return a.field < b.field
	})

	var b strings.Builder
	b.WriteString("% Auto-generated by cmd/render — the cross-scenario field profile (m3 input).\n")
	b.WriteString("% Per canonical field-key over SCORED scenarios: n = scenarios measured,\n")
	b.WriteString("% dec = times it was a deciding locus (excluded from the map there), then\n")
	b.WriteString("% the saliency distribution over its NON-deciding appearances and how many\n")
	b.WriteString("% of those were signal (McNemar+BH+floor). A key deciding in one scenario\n")
	b.WriteString("% and flat everywhere else carries reference-resolution signal, not a\n")
	b.WriteString("% generator artifact — this table is the anti-circularity defense.\n")
	b.WriteString("% \\input-able fragment; requires \\usepackage{booktabs,longtable}.\n")
	b.WriteString("\\begin{longtable}{llrrrrrr}\n\\toprule\nKind & Field & n & dec & mean & min & max & signal \\\\\n\\midrule\n\\endhead\n")
	for _, pk := range keys {
		p := profs[pk]
		mean, lo, hi := "--", "--", "--"
		if p.nonDeciding > 0 {
			mean = fmt.Sprintf("%.2f", frac1(p.sum, p.nonDeciding))
			lo = fmt.Sprintf("%.2f", p.minSal)
			hi = fmt.Sprintf("%.2f", p.maxSal)
		}
		field := "\\texttt{" + escapeTeX(p.field) + "}"
		if p.nSig > 0 {
			field = "\\textbf{" + field + "}"
		}
		fmt.Fprintf(&b, "%s & %s & %d & %d & %s & %s & %s & %d \\\\\n",
			escapeTeX(p.kind), field, p.measured, p.deciding, mean, lo, hi, p.nSig)
	}
	b.WriteString("\\bottomrule\n\\end{longtable}\n")
	writeFile(filepath.Join(outDir, "fieldprofile.gen.tex"), b.String())
}

// writeHeatmapFig emits the contrast map as TikZ: one grid per Kind, columns =
// scored scenarios containing that Kind, rows = the Kind's field-keys, hottest
// first. Orange = signal, grey = measured but no marginal signal (the sea of
// grey IS the result: those fields are candidates for reduce()), dashed = the
// negative-control cells defining the fragility floor, dark + * = deciding.
func (f *figCtx) writeHeatmapFig(outDir string) {
	type entry struct {
		c   cell
		key string
	}
	type grid struct {
		kind      string
		scenarios []string
		fields    []string
		at        map[string]entry
		max       float64
	}
	grids := map[string]*grid{}
	for _, key := range f.order {
		c := f.cells[key]
		if !f.scored(c) {
			continue
		}
		g := grids[c.kind]
		if g == nil {
			g = &grid{kind: c.kind, at: map[string]entry{}}
			grids[c.kind] = g
		}
		k := c.field + "\x00" + c.scenario
		if old, ok := g.at[k]; !ok || f.sal(c) > f.sal(old.c) {
			g.at[k] = entry{c, key}
		}
		if !c.deciding && f.sal(c) > g.max {
			g.max = f.sal(c)
		}
	}
	var kinds []*grid
	for _, g := range grids {
		seenF, seenS := map[string]bool{}, map[string]bool{}
		heat := map[string]float64{}
		for k, e := range g.at {
			parts := strings.SplitN(k, "\x00", 2)
			if !seenF[parts[0]] {
				seenF[parts[0]] = true
				g.fields = append(g.fields, parts[0])
			}
			if !seenS[parts[1]] {
				seenS[parts[1]] = true
				g.scenarios = append(g.scenarios, parts[1])
			}
			if !e.c.deciding && f.sal(e.c) > heat[parts[0]] {
				heat[parts[0]] = f.sal(e.c)
			}
		}
		sort.Strings(g.scenarios)
		sort.Slice(g.fields, func(i, j int) bool {
			if heat[g.fields[i]] != heat[g.fields[j]] {
				return heat[g.fields[i]] > heat[g.fields[j]]
			}
			return g.fields[i] < g.fields[j]
		})
		kinds = append(kinds, g)
	}
	sort.Slice(kinds, func(i, j int) bool {
		if kinds[i].max != kinds[j].max {
			return kinds[i].max > kinds[j].max
		}
		return kinds[i].kind < kinds[j].kind
	})

	var b strings.Builder
	b.WriteString("% Auto-generated by cmd/render — the contrast map as a TikZ figure.\n")
	b.WriteString("% One grid per Kind over the scored scenarios. Orange = signal (verdict\n")
	b.WriteString("% from fdr.gen.tex), grey = measured, no marginal signal (deeper grey =\n")
	b.WriteString("% higher raw saliency, i.e. destabilization), dashed outline = negative\n")
	b.WriteString("% control (defines the fragility floor), dark cell with * = deciding locus\n")
	b.WriteString("% (the injected fault, never scored).\n")
	b.WriteString("% \\input-able fragment; requires \\usepackage{tikz}.\n")
	for _, g := range kinds {
		fmt.Fprintf(&b, "\n\\par\\medskip\\noindent{\\small\\bfseries %s}\\par\\smallskip\n", escapeTeX(g.kind))
		b.WriteString("\\begin{tikzpicture}[x=3.4mm,y=3.4mm]\n")
		for ci, s := range g.scenarios {
			fmt.Fprintf(&b, "\\node[rotate=45,anchor=west,font=\\ttfamily\\tiny] at (%d.5,0.25) {%s};\n", ci, escapeTeX(s))
		}
		for ri, field := range g.fields {
			fmt.Fprintf(&b, "\\node[anchor=east,font=\\ttfamily\\tiny] at (-0.15,-%d.5) {%s};\n", ri, escapeTeX(field))
			for ci, s := range g.scenarios {
				e, ok := g.at[field+"\x00"+s]
				if !ok {
					continue
				}
				c := e.c
				x, y := ci, -(ri + 1)
				if c.deciding {
					fmt.Fprintf(&b, "\\fill[fill={rgb,255:red,51;green,65;blue,85}] (%d,%d) rectangle ++(1,1);\n", x, y)
					fmt.Fprintf(&b, "\\node[white,font=\\tiny] at (%d.5,%d.5) {$\\ast$};\n", x, y)
					continue
				}
				verdict := f.verdict(e.key)
				r, gg, bb := verdictRGB(verdict, f.sal(c))
				fmt.Fprintf(&b, "\\fill[fill={rgb,255:red,%d;green,%d;blue,%d}] (%d,%d) rectangle ++(1,1);\n", r, gg, bb, x, y)
				if verdict == "control" {
					fmt.Fprintf(&b, "\\draw[gray,dashed,line width=0.2pt] (%d,%d) rectangle ++(1,1);\n", x, y)
				}
			}
		}
		fmt.Fprintf(&b, "\\draw[gray!50,line width=0.2pt] (0,0) grid (%d,-%d);\n", len(g.scenarios), len(g.fields))
		b.WriteString("\\end{tikzpicture}\n")
	}
	writeFile(filepath.Join(outDir, "heatmapfig.gen.tex"), b.String())
}

// writeManifestFig paints the flagship scenario's YAML line by line. The
// flagship is chosen FROM THE DATA — the scored scenario with the most signal
// cells (ties by max saliency) — never hand-picked.
func (f *figCtx) writeManifestFig(outDir string) {
	nSig, maxSal := map[string]int{}, map[string]float64{}
	for _, key := range f.order {
		c := f.cells[key]
		if !f.scored(c) || c.deciding {
			continue
		}
		if f.verdict(key) == "signal" {
			nSig[c.scenario]++
		}
		maxSal[c.scenario] = math.Max(maxSal[c.scenario], f.sal(c))
	}
	flagship := ""
	for s := range nSig {
		if flagship == "" || nSig[s] > nSig[flagship] ||
			(nSig[s] == nSig[flagship] && maxSal[s] > maxSal[flagship]) {
			flagship = s
		}
	}
	if flagship == "" {
		return // no scored data yet — nothing to paint
	}
	var scen *dataset.Scenario
	for _, s := range dataset.All() {
		if s.Name == flagship {
			s := s
			scen = &s
		}
	}
	if scen == nil {
		return
	}

	var b strings.Builder
	b.WriteString("% Auto-generated by cmd/render — the heatmap painted on the manifest.\n")
	fmt.Fprintf(&b, "%% Flagship scenario (most signal cells, data-chosen): %s.\n", flagship)
	b.WriteString("% Orange = signal, grey = measured no-signal (deeper = higher saliency),\n")
	b.WriteString("% dark = deciding locus (*). Right gutter: the cell's saliency.\n")
	b.WriteString("% \\input-able fragment; requires \\usepackage{xcolor}.\n")
	b.WriteString("\\begingroup\\setlength{\\parskip}{0pt}\\setlength{\\parindent}{0pt}\\setlength{\\fboxsep}{0pt}\n")

	lines := strings.Split(strings.TrimRight(scen.YAML, "\n"), "\n")
	type mark struct {
		c   cell
		key string
	}
	byLine := map[int]mark{}
	offset := 0
	for doc, src := range splitDocs(scen.YAML) {
		var root yaml.Node
		if err := yaml.Unmarshal([]byte(src), &root); err == nil && len(root.Content) > 0 {
			walkYAML(nil, root.Content[0], "", func(ptr string, from, to int) {
				key := scen.Name + "\x00" + fmt.Sprint(doc) + "\x00" + heatmap.NormalizeKey(ptr)
				if c, ok := f.cells[key]; ok {
					for l := from; l <= to; l++ {
						byLine[offset+l] = mark{c, key}
					}
				}
			})
		}
		offset += strings.Count(src, "\n") + 2 // body lines + the --- separator
	}

	for i, line := range lines {
		text := texLine(line)
		m, ok := byLine[i+1]
		if !ok {
			fmt.Fprintf(&b, "\\colorbox[HTML]{FFFFFF}{\\makebox[\\linewidth][l]{\\scriptsize\\ttfamily %s}}\\par\n", text)
			continue
		}
		if m.c.deciding {
			fmt.Fprintf(&b, "\\colorbox[HTML]{334155}{\\makebox[\\linewidth][l]{\\scriptsize\\ttfamily\\color{white} %s~~$\\ast$}}\\par\n", text)
			continue
		}
		verdict, s := f.verdict(m.key), f.sal(m.c)
		r, gg, bb := verdictRGB(verdict, s)
		fg := ""
		if verdict == "signal" {
			fg = "\\color{white}"
		}
		fmt.Fprintf(&b, "\\colorbox[HTML]{%02X%02X%02X}{\\makebox[\\linewidth][l]{\\scriptsize\\ttfamily%s %s~~%.2f}}\\par\n",
			r, gg, bb, fg, text, s)
	}
	b.WriteString("\\endgroup\n")
	writeFile(filepath.Join(outDir, "manifestfig.gen.tex"), b.String())
}

// splitDocs and walkYAML mirror cmd/viewer (per-cmd duplication of small pure
// helpers, like frac): the shards say WHAT was measured, the AST says WHERE.

func splitDocs(yamlSrc string) []string {
	var docs []string
	var cur []string
	for _, line := range strings.Split(strings.TrimRight(yamlSrc, "\n"), "\n") {
		if strings.TrimSpace(line) == "---" {
			docs = append(docs, strings.Join(cur, "\n"))
			cur = nil
			continue
		}
		cur = append(cur, line)
	}
	return append(docs, strings.Join(cur, "\n"))
}

func walkYAML(key, val *yaml.Node, ptr string, mark func(ptr string, from, to int)) {
	from := val.Line
	if key != nil {
		from = key.Line
	}
	mark(ptr, from, maxNodeLine(val))
	switch val.Kind {
	case yaml.MappingNode:
		for i := 0; i+1 < len(val.Content); i += 2 {
			walkYAML(val.Content[i], val.Content[i+1], ptr+"/"+val.Content[i].Value, mark)
		}
	case yaml.SequenceNode:
		for i, c := range val.Content {
			walkYAML(nil, c, fmt.Sprintf("%s/%d", ptr, i), mark)
		}
	}
}

func maxNodeLine(n *yaml.Node) int {
	m := n.Line
	for _, c := range n.Content {
		if l := maxNodeLine(c); l > m {
			m = l
		}
	}
	return m
}

// verdictRGB is the figure palette: signal = strong orange scaled slightly
// deeper with saliency; everything else grey scaled darker with raw saliency.
func verdictRGB(verdict string, sal float64) (int, int, int) {
	sal = math.Max(0, math.Min(1, sal))
	if verdict == "signal" {
		return hslRGB(24, 0.94, (62-14*sal)/100)
	}
	return hslRGB(220, 0.09, (96-42*sal)/100)
}

// hslRGB converts HSL (h in degrees) to 8-bit RGB.
func hslRGB(h, s, l float64) (int, int, int) {
	c := (1 - math.Abs(2*l-1)) * s
	x := c * (1 - math.Abs(math.Mod(h/60, 2)-1))
	m := l - c/2
	var r, g, b float64
	switch {
	case h < 60:
		r, g, b = c, x, 0
	case h < 120:
		r, g, b = x, c, 0
	case h < 180:
		r, g, b = 0, c, x
	case h < 240:
		r, g, b = 0, x, c
	case h < 300:
		r, g, b = x, 0, c
	default:
		r, g, b = c, 0, x
	}
	return int(math.Round((r + m) * 255)), int(math.Round((g + m) * 255)), int(math.Round((b + m) * 255))
}

// texLine escapes one YAML line for \texttt inside \makebox: TeX specials
// escaped, spaces made visible-width with ~ (non-breaking, space-width in tt).
func texLine(line string) string {
	return strings.ReplaceAll(escapeTeX(line), " ", "~")
}

// frac1 is frac for float sums.
func frac1(sum float64, n int) float64 {
	if n == 0 {
		return 0
	}
	return sum / float64(n)
}

func writeFile(path, content string) {
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write %s: %v\n", path, err)
		os.Exit(1)
	}
	fmt.Printf("wrote %s\n", path)
}
