// Command render reads the raw per-trial JSONL shards produced by cmd/heatmap and
// renders the saliency table to paper/heatmap.gen.tex. Accuracy (fraction correct
// over a cell's trials) and saliency (baseline − reduced) are computed here, so
// the slow model calls are never repeated when the methodology changes. Merging
// is just reading every shard, grouped by (scenario, doc, field).
//
//	go run ./cmd/render -in data -out paper
package main

import (
	"bufio"
	"encoding/json"
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/mikolajsemeniuk/kubelean/pkg/heatmap"
)

// cell aggregates all reduced trials for one (scenario, doc, field).
type cell struct {
	scenario string
	kind     string
	field    string
	category string
	valid    bool
	correct  int
	total    int
}

func main() {
	in := flag.String("in", "data", "directory of JSONL shards")
	out := flag.String("out", "paper", "output directory")
	flag.Parse()

	paths, err := filepath.Glob(filepath.Join(*in, "*.jsonl"))
	if err != nil {
		log.Fatal(err)
	}
	sort.Strings(paths)

	var recs []heatmap.Record
	for _, p := range paths {
		f, err := os.Open(p)
		if err != nil {
			log.Fatal(err)
		}

		sc := bufio.NewScanner(f)
		sc.Buffer(make([]byte, 0, 64*1024), 4*1024*1024) // raw responses can be long
		for sc.Scan() {
			if len(sc.Bytes()) == 0 {
				continue
			}

			var r heatmap.Record
			if err := json.Unmarshal(sc.Bytes(), &r); err != nil {
				log.Fatalf("%s: %v", p, err)
			}

			recs = append(recs, r)
		}

		if err := sc.Err(); err != nil {
			log.Fatal(err)
		}

		f.Close()
	}

	if len(recs) == 0 {
		log.Fatalf("no records in %s — produce shards first (make run-<group>)", *in)
	}

	baseCorrect := map[string]int{}
	baseTotal := map[string]int{}
	cells := map[string]cell{}
	var order []string
	digests := map[string]bool{}

	for _, r := range recs {
		digests[r.ModelDigest] = true
		correct := r.Answer != nil && *r.Answer == r.FaultClass

		if r.Variant == "baseline" {
			baseTotal[r.Scenario]++
			if correct {
				baseCorrect[r.Scenario]++
			}
			continue
		}

		field, doc := "", -1
		if r.Field != nil {
			field = *r.Field
		}
		if r.Doc != nil {
			doc = *r.Doc
		}

		key := fmt.Sprintf("%s\x00%d\x00%s", r.Scenario, doc, field)
		c, seen := cells[key]
		if !seen {
			c = cell{scenario: r.Scenario, kind: r.Kind, field: field, category: r.Category, valid: r.Valid}
			order = append(order, key)
		}

		c.total++
		if correct {
			c.correct++
		}

		cells[key] = c
	}

	if len(digests) > 1 {
		log.Printf("warning: shards mix %d model digests — saliency across them is not comparable", len(digests))
	}

	meta := recs[0]
	var b strings.Builder
	b.WriteString("% Auto-generated by cmd/render from data/*.jsonl — do not edit.\n")
	b.WriteString("% \\input-able fragment; requires \\usepackage{booktabs}.\n")
	fmt.Fprintf(&b, "%% model: %s @ %s ; k=%d ; temp=%.2f ; num_ctx=%d\n", meta.Model, meta.ModelDigest, meta.K, meta.Temp, meta.NumCtx)
	b.WriteString("% Saliency = baseline accuracy − reduced accuracy, each a fraction over the cell's trials.\n")
	b.WriteString("% Bold = saliency > 0 (placeholder; a CI test replaces it).\n")
	b.WriteString("% Valid is a covariate, NOT a gate: every variant is scored; Valid=no is a separate population.\n")
	b.WriteString("\\begin{tabular}{lllcr}\n\\toprule\n")
	b.WriteString("Scenario & Kind & Field & Valid & Saliency \\\\\n\\midrule\n")

	for _, key := range order {
		c := cells[key]
		saliency := frac(baseCorrect[c.scenario], baseTotal[c.scenario]) - frac(c.correct, c.total)

		field := "\\texttt{" + escapeTeX(c.field) + "}"
		if saliency > 0 {
			field = "\\textbf{" + field + "}"
		}

		mark := "yes"
		if !c.valid {
			mark = "no"
		}

		fmt.Fprintf(&b, "%s & %s & %s & %s & %.2f \\\\\n", escapeTeX(c.scenario), escapeTeX(c.kind), field, mark, saliency)
	}

	b.WriteString("\\bottomrule\n\\end{tabular}\n")
	if err := os.MkdirAll(*out, 0o755); err != nil {
		log.Fatal(err)
	}

	path := filepath.Join(*out, "heatmap.gen.tex")
	if err := os.WriteFile(path, []byte(b.String()), 0o644); err != nil {
		log.Fatalf("write %s: %v", path, err)
	}

	fmt.Printf("wrote %s (%d cells from %d trials)\n", path, len(order), len(recs))
}

func frac(num, den int) float64 {
	if den == 0 {
		return 0
	}

	return float64(num) / float64(den)
}

func escapeTeX(s string) string {
	in := []string{
		"\\", "\\textbackslash{}",
		"_", "\\_", "%", "\\%", "&", "\\&", "#", "\\#",
		"$", "\\$", "{", "\\{", "}", "\\}",
		"~", "\\textasciitilde{}", "^", "\\textasciicircum{}",
	}

	return strings.NewReplacer(in...).Replace(s)
}
