// Command render reads the raw per-trial JSONL shards produced by cmd/heatmap and
// renders paper/heatmap.gen.tex. Accuracy and saliency are computed here, not at
// produce time, so the slow model calls are never repeated when the methodology
// changes.
//
// It partitions fields into two populations (the flip): a field whose removal
// deletes the fault is a deciding-field locus — its expected answer is NOT the
// scenario's fault but NoFaultFound, since the fault is gone. Scoring those as
// "missed the fault" would mechanically yield saliency 1.00 and falsely read as
// signal. So deciding loci go to a separate control table (how often the model
// recognizes the fault is gone); the main saliency table holds only non-deciding
// fields. Deciding loci are resolved from each scenario's ground truth via
// heatmap.ResolveLeaves.
//
//	go run ./cmd/render -in data -out paper
package main

import (
	"bufio"
	"encoding/json"
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/mikolajsemeniuk/kubelean/pkg/dataset"
	"github.com/mikolajsemeniuk/kubelean/pkg/heatmap"
)

const noFault = "NoFaultFound"

// cell aggregates all reduced trials for one (scenario, doc, field).
type cell struct {
	scenario     string
	kind         string
	field        string
	valid        bool
	deciding     bool
	total        int
	matchFault   int // answer == scenario fault (saliency uses this)
	matchNoFault int // answer == NoFaultFound (control "recognized" uses this)
}

func main() {
	in := flag.String("in", "data", "directory of JSONL shards")
	out := flag.String("out", "paper", "output directory")
	flag.Parse()

	recs := readShards(*in)
	if len(recs) == 0 {
		log.Fatalf("no records in %s — produce shards first (make run-<group>)", *in)
	}

	// Resolve each scenario's deciding-field loci to concrete (doc, pointer).
	deciding := map[string][]heatmap.Locus{}
	for _, s := range dataset.All() {
		for _, df := range s.DecidingFields {
			ls, err := heatmap.ResolveLeaves(s.YAML, df.Kind, df.Path)
			if err != nil {
				log.Fatalf("resolve %s %s: %v", s.Name, df.Path, err)
			}
			deciding[s.Name] = append(deciding[s.Name], ls...)
		}
	}

	baseCorrect := map[string]int{}
	baseTotal := map[string]int{}
	cells := map[string]cell{}
	var order []string
	digests := map[string]bool{}

	for _, r := range recs {
		digests[r.ModelDigest] = true

		if r.Variant == "baseline" {
			baseTotal[r.Scenario]++
			if r.Answer != nil && *r.Answer == r.FaultClass {
				baseCorrect[r.Scenario]++
			}
			continue
		}

		field, doc := "", -1
		if r.Field != nil {
			field = *r.Field
		}
		if r.Doc != nil {
			doc = *r.Doc
		}

		key := fmt.Sprintf("%s\x00%d\x00%s", r.Scenario, doc, field)
		c, seen := cells[key]
		if !seen {
			c = cell{
				scenario: r.Scenario, kind: r.Kind, field: field, valid: r.Valid,
				deciding: decides(doc, field, deciding[r.Scenario]),
			}
			order = append(order, key)
		}
		c.total++
		if r.Answer != nil && *r.Answer == r.FaultClass {
			c.matchFault++
		}
		if r.Answer != nil && *r.Answer == noFault {
			c.matchNoFault++
		}
		cells[key] = c
	}

	if len(digests) > 1 {
		log.Printf("warning: shards mix %d model digests — saliency across them is not comparable", len(digests))
	}

	meta := recs[0]
	var b strings.Builder
	b.WriteString("% Auto-generated by cmd/render from data/*.jsonl — do not edit.\n")
	b.WriteString("% \\input-able fragment; requires \\usepackage{booktabs}.\n")
	fmt.Fprintf(&b, "%% model: %s @ %s ; k=%d ; temp=%.2f ; num_ctx=%d\n", meta.Model, meta.ModelDigest, meta.K, meta.Temp, meta.NumCtx)

	// Population 1: the saliency map — non-deciding fields only.
	b.WriteString("% Table 1 — saliency map (non-deciding fields). Saliency = baseline accuracy\n")
	b.WriteString("% − reduced accuracy, each a fraction over the cell's trials; bold = saliency > 0.\n")
	b.WriteString("% Valid is a covariate, not a gate: Valid=no is scored but flagged.\n")
	b.WriteString("\\begin{tabular}{lllcr}\n\\toprule\nScenario & Kind & Field & Valid & Saliency \\\\\n\\midrule\n")
	for _, key := range order {
		c := cells[key]
		if c.deciding {
			continue
		}
		saliency := frac(baseCorrect[c.scenario], baseTotal[c.scenario]) - frac(c.matchFault, c.total)
		field := "\\texttt{" + escapeTeX(c.field) + "}"
		if saliency > 0 {
			field = "\\textbf{" + field + "}"
		}
		fmt.Fprintf(&b, "%s & %s & %s & %s & %.2f \\\\\n", escapeTeX(c.scenario), escapeTeX(c.kind), field, validMark(c.valid), saliency)
	}
	b.WriteString("\\bottomrule\n\\end{tabular}\n\n")

	// Population 2: the control — deciding loci, where the flip makes expected =
	// NoFaultFound. Recognized = fraction of trials that correctly returned it.
	b.WriteString("% Table 2 — control: deciding-field loci. Removing these deletes the fault, so\n")
	b.WriteString("% expected flips to NoFaultFound; Recognized = fraction that returned it (the rest\n")
	b.WriteString("% hallucinated the now-absent fault). Not saliency — these are not in the map.\n")
	b.WriteString("\\begin{tabular}{lllcr}\n\\toprule\nScenario & Kind & Field & Valid & Recognized \\\\\n\\midrule\n")
	for _, key := range order {
		c := cells[key]
		if !c.deciding {
			continue
		}
		recognized := frac(c.matchNoFault, c.total)
		fmt.Fprintf(&b, "%s & %s & \\texttt{%s} & %s & %.2f \\\\\n", escapeTeX(c.scenario), escapeTeX(c.kind), escapeTeX(c.field), validMark(c.valid), recognized)
	}
	b.WriteString("\\bottomrule\n\\end{tabular}\n")

	if err := os.MkdirAll(*out, 0o755); err != nil {
		log.Fatal(err)
	}
	path := filepath.Join(*out, "heatmap.gen.tex")
	if err := os.WriteFile(path, []byte(b.String()), 0o644); err != nil {
		log.Fatalf("write %s: %v", path, err)
	}
	fmt.Printf("wrote %s (%d cells from %d trials)\n", path, len(order), len(recs))
}

// decides reports whether the field at (doc, pointer) is an ancestor-or-equal of
// a concrete deciding locus in the same document — i.e. removing it removes the
// fault.
func decides(doc int, field string, loci []heatmap.Locus) bool {
	for _, l := range loci {
		if l.Doc == doc && (field == l.Pointer || strings.HasPrefix(l.Pointer, field+"/")) {
			return true
		}
	}
	return false
}

func readShards(dir string) []heatmap.Record {
	paths, err := filepath.Glob(filepath.Join(dir, "*.jsonl"))
	if err != nil {
		log.Fatal(err)
	}
	sort.Strings(paths)

	var recs []heatmap.Record
	for _, p := range paths {
		f, err := os.Open(p)
		if err != nil {
			log.Fatal(err)
		}

		sc := bufio.NewScanner(f)
		sc.Buffer(make([]byte, 0, 64*1024), 4*1024*1024) // raw responses can be long
		for sc.Scan() {
			if len(sc.Bytes()) == 0 {
				continue
			}
			var r heatmap.Record
			if err := json.Unmarshal(sc.Bytes(), &r); err != nil {
				log.Fatalf("%s: %v", p, err)
			}
			recs = append(recs, r)
		}
		if err := sc.Err(); err != nil {
			log.Fatal(err)
		}
		f.Close()
	}
	return recs
}

func frac(num, den int) float64 {
	if den == 0 {
		return 0
	}
	return float64(num) / float64(den)
}

func validMark(ok bool) string {
	if ok {
		return "yes"
	}
	return "no"
}

func escapeTeX(s string) string {
	in := []string{
		"\\", "\\textbackslash{}",
		"_", "\\_", "%", "\\%", "&", "\\&", "#", "\\#",
		"$", "\\$", "{", "\\{", "}", "\\}",
		"~", "\\textasciitilde{}", "^", "\\textasciicircum{}",
	}

	return strings.NewReplacer(in...).Replace(s)
}
