// Command perclass runs the RCA benchmark and reports accuracy per fault class
// across distillation profiles — the per-class heterogeneity that motivates
// goal-conditioned distillation (H5): some classes improve sharply under pruning,
// others regress, bundles sit at the model-capacity floor. Writes
// paper/perclass.gen.tex.
//
// Usage:
//
//	go run ./cmd/perclass -model qwen2.5:7b-instruct -n 3 -k 3 [-l4]
package main

import (
	"context"
	"flag"
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/schollz/progressbar/v3"

	"github.com/mikolajsemeniuk/kubelean/pkg/bench"
	"github.com/mikolajsemeniuk/kubelean/pkg/distill"
	"github.com/mikolajsemeniuk/kubelean/pkg/eval"
	"github.com/mikolajsemeniuk/kubelean/pkg/faults"
)

func main() {
	model := flag.String("model", "qwen2.5:7b-instruct", "Ollama model")
	n := flag.Int("n", 3, "instances per class")
	k := flag.Int("k", 3, "RCA repeats per instance per profile")
	temp := flag.Float64("temp", 0.4, "sampling temperature")
	l3thresh := flag.Float64("l3thresh", 0.0, "L3 entropy threshold")
	l4 := flag.Bool("l4", false, "include the L4 goal-conditioned profile (needs an embed model)")
	embedModel := flag.String("embed", "nomic-embed-text", "Ollama embedding model for L4")
	l4thresh := flag.Float64("l4thresh", 0.5, "L4 cosine-similarity keep threshold")
	texOut := flag.String("tex", "paper/perclass.gen.tex", "write the LaTeX table here (empty = skip)")
	flag.Parse()

	instances := faults.GenerateAll(*n)
	profiles := []string{bench.L0, bench.L1, bench.L2, bench.L3}
	if *l4 {
		profiles = append(profiles, bench.L4)
	}
	profiles = append(profiles, bench.Rand)

	var embed distill.EmbedFunc
	if *l4 {
		embed = distill.NewEmbedder(*embedModel).Embed
		fmt.Printf("L4 grounding via %s (threshold %.2f)\n", *embedModel, *l4thresh)
	}
	r := bench.NewRenderer(bench.Corpus(instances), embed, *l3thresh, *l4thresh)

	client := eval.NewRCAClient(*model, *temp)
	diag := func(ctx context.Context, y string) (string, int, error) {
		d, ptok, _, err := client.Diagnose(ctx, y)
		return d.RootCauseLabel, ptok, err
	}

	fmt.Printf("model=%s  n=%d  k=%d  temp=%.2f  profiles=%s  instances=%d\n\n",
		*model, *n, *k, *temp, strings.Join(profiles, "/"), len(instances))

	renderBar := progressbar.NewOptions(len(instances),
		progressbar.OptionSetDescription("render"), progressbar.OptionSetWriter(os.Stderr), progressbar.OptionClearOnFinish())
	rcaBar := progressbar.NewOptions(len(instances)*len(profiles)**k,
		progressbar.OptionSetDescription("RCA"), progressbar.OptionSetWriter(os.Stderr),
		progressbar.OptionShowCount(), progressbar.OptionSetPredictTime(true),
		progressbar.OptionThrottle(100*time.Millisecond), progressbar.OptionClearOnFinish())

	results, err := bench.Run(context.Background(), instances, profiles, r, diag, *k,
		bench.Progress{Render: func() { _ = renderBar.Add(1) }, RCA: func() { _ = rcaBar.Add(1) }})
	if err != nil {
		fatal("run: %v", err)
	}

	byClass := map[string]*bench.Acc{} // "label/profile"
	for _, res := range results {
		key := res.Label + "/" + res.Profile
		if byClass[key] == nil {
			byClass[key] = &bench.Acc{}
		}
		byClass[key].Add(res)
	}

	fmt.Printf("== by class (%s) ==\n", strings.Join(profiles, " -> "))
	for _, fc := range faults.Catalog() {
		if byClass[fc.Label+"/"+profiles[0]] == nil {
			continue
		}
		fmt.Printf("  %-30s %-4s ", fc.Label, fc.Difficulty)
		for _, p := range profiles {
			fmt.Printf(" %3.0f%%", byClass[fc.Label+"/"+p].Pct())
		}
		fmt.Println()
	}

	if *texOut != "" {
		if err := bench.WriteFile(*texOut, perclassTeX(*model, *n, *k, *temp, profiles, byClass)); err != nil {
			fatal("write tex: %v", err)
		}
		fmt.Printf("\nwrote LaTeX: %s\n", *texOut)
	}
}

func perclassTeX(model string, n, k int, temp float64, profiles []string, byClass map[string]*bench.Acc) string {
	var b strings.Builder
	fmt.Fprintf(&b, "%% perclass.gen.tex — AUTO-GENERATED by cmd/perclass. DO NOT EDIT BY HAND.\n")
	fmt.Fprintf(&b, "%% Requires \\usepackage{booktabs}.\n\n")
	fmt.Fprintf(&b, "\\begin{table}[t]\n  \\centering\n")
	fmt.Fprintf(&b, "  \\caption{RCA accuracy (\\%%) per fault class across distillation profiles (\\texttt{%s}, $n{=}%d$, $k{=}%d$, $T{=}%.2f$).}\n", bench.TexEscape(model), n, k, temp)
	fmt.Fprintf(&b, "  \\label{tab:perclass}\n")
	fmt.Fprintf(&b, "  \\begin{tabular}{ll%s}\n    \\toprule\n    Fault class & Diff.", strings.Repeat("r", len(profiles)))
	for _, p := range profiles {
		fmt.Fprintf(&b, " & %s", p)
	}
	fmt.Fprintf(&b, " \\\\\n    \\midrule\n")
	for _, fc := range faults.Catalog() {
		if byClass[fc.Label+"/"+profiles[0]] == nil {
			continue
		}
		fmt.Fprintf(&b, "    %s & %s", bench.TexEscape(fc.Label), fc.Difficulty)
		for _, p := range profiles {
			fmt.Fprintf(&b, " & %.0f", byClass[fc.Label+"/"+p].Pct())
		}
		fmt.Fprintf(&b, " \\\\\n")
	}
	fmt.Fprintf(&b, "    \\bottomrule\n  \\end{tabular}\n\\end{table}\n")
	return b.String()
}

func fatal(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "perclass: "+format+"\n", args...)
	os.Exit(1)
}
